### ISSUE TITLE
能问问什么原理实现的么

### ISSUE THREAD

**Issue by mengyyy** [fkzhang/WechatCloudBackup#2]
主要担心信息泄露

**Comment by mengyyy** [comment]
6.3.9 Nexus5  安卓6.0 没有变化

**Comment by fkzhang** [comment]
我不保存任何信息 公开源代码也是想证明这点 
这是用微信官方的服务 
新版微信把这功能隐藏了
你按打开恢复时 旧版本会跳到 com.tencent.mm.plugin.backup.ui.BakChatUI
可是新版本跳到 com.tencent.mm.plugin.backup.moveui.BakMoveUI 去了
我只是也叫新版本跳到BakChatUI那里然后显示上传的按钮

6.3.9 我是测试过的 能行 不过只是在kitkat上面 （5.0 以下）没有6.0的不能测试
你看看xposed日志 有没有提示哪里出错了

**Comment by mayourt** [comment]
的确你说的那样，6.0的xposed的log里面有一连串的错误。问一下，你是要开机后的系统的log还是xposed的log，我一会邮箱发给你。

**Comment by fkzhang** [comment]
我想我知道问题在哪 可是我没有6.0的安卓可以测试 你能帮我测试一下这个能否解决问题
[app-release.zip](https://github.com/fkzhang/WechatCloudBackup/files/104568/app-release.zip)

**Comment by mayourt** [comment]
嗯嗯，修复了，在我的安卓6.0上正常了。

**Comment by mengyyy** [comment]
我的依旧不行  看看需要什么数据

**Comment by fkzhang** [comment]
xposed log

**Comment by mengyyy** [comment]
01-27 22:32:55.495 I/Xposed  (  218): -----------------
01-27 22:32:55.495 I/Xposed  (  218): Starting Xposed version 79, compiled for SDK 23
01-27 22:32:55.495 I/Xposed  (  218): Device: Nexus 5 (LGE), Android version 6.0.1 (SDK 23)
01-27 22:32:55.495 I/Xposed  (  218): ROM: MMB29S
01-27 22:32:55.495 I/Xposed  (  218): Build fingerprint: google/hammerhead/hammerhead:6.0.1/MMB29S/2489379:user/release-keys
01-27 22:32:55.495 I/Xposed  (  218): Platform: armeabi-v7a, 32-bit binary, system server: yes
01-27 22:32:55.495 I/Xposed  (  218): SELinux enabled: yes, enforcing: yes
01-27 22:32:55.563 I/Xposed  (  218): -----------------
01-27 22:32:55.564 I/Xposed  (  218): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-27 22:32:56.414 I/Xposed  (  218): Detected ART runtime
01-27 22:32:56.460 I/Xposed  (  218): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
01-27 22:32:56.932 I/Xposed  (  218): Loading modules from /data/app/com.fkzhang.wechatcloudbackup-2/base.apk
01-27 22:32:57.178 I/Xposed  (  218):   Loading class com.fkzhang.wechatcloudbackup.XposedInit

**Comment by mengyyy** [comment]
![image](https://cloud.githubusercontent.com/assets/10589755/12616521/a2500d58-c546-11e5-8866-04e2aa2af58a.png)

**Comment by fkzhang** [comment]
日志里没有出现什么问题 你点击 回复聊天记录无效吗？

**Comment by mengyyy** [comment]
擦 没有点进去……可以的

**Comment by mengyyy** [comment]
我这6.0的上传备份可以
